# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
test:
  adapter: postgresql
  encoding: unicode
  database: Go_test
  pool: 5
  username: kaichimomose
  password:


development:
    adapter: postgresql
    encoding: unicode
    database: Go_development
    pool: 5
    username: kaichimomose
    password:
